jabber/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'jabber/create'

  get 'jabber/show'

  get 'user/index'

  resources :friendships

  devise_for :users

root to: "user#index"
get "jabber/index" => "jabber#index", as: "list"
post "jabber/create" => "jabber#create", as: "jabbers"
get "edit" => "user#edit", as: "edit_user"
patch "update" => "user#update", as: "user"
get "show" => "user#show", as: "show_user"
get "following" => "friendships#following", as: "following"
get "follower" => "friendships#follower", as: "follower"

end

jabber/app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

jabber/app/models/jabber.rb
class Jabber < ActiveRecord::Base
  belongs_to :user
end

jabber/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :followers, :through => :inverse_friendships, :source => :user
  has_many :jabbers

  def get_name
    if self.name.blank?
      ret_name = self.email
    else
      ret_name = self.name
    end
  end

end

jabber/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create

    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Friendship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def following
    @following = current_user.friendships
  end

  def follower
    @follower = current_user.inverse_friendships
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id)
    end
end

jabber/app/controllers/jabber_controller.rb
class JabberController < ApplicationController
  before_action :set_jabber, only: [:index]

  def index
    @jabber = Jabber.new
    redirect_to root_path
  end

  def new
  end

  def create
    @jabber = current_user.jabbers.build(jabber_params)
    if @jabber.save
      redirect_to list_path
    end
  end

  def show
  end

  private
  def set_jabber
    @jabbers = current_user.jabbers.order(created_at: :desc) if user_signed_in?
  end

  def jabber_params
    params.require(:jabber).permit(:message)
  end
end

jabber/app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :create, :update, :edit, :delete, :index]

  def index
    my_users = Array.new
    my_jabbers = Array.new

    my_users << current_user
    my_jabbers << Jabber.where(user_id: current_user.id)

    current_user.friends.each do |friend|
      my_users << friend
      my_jabbers << Jabber.where(user_id: friend.id)
    end

    my_jabbers.flatten!

    @new_friends = User.all - my_users
    @all_my_jabbers = my_jabbers.sort_by(&:created_at).reverse
    @jabber = Jabber.new
  end

  def show
  end

  def update
    if current_user.update(user_params)
      redirect_to show_user_path, notice: 'User profile successfuly updated'
    else
      render show
    end
  end


  def edit
    @user = current_user
  end

  private
  def user_params
    params.require(:user).permit(:name, :description, :location)
  end

end

jabber/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

jabber/app/helpers/jabber_helper.rb
module JabberHelper
end

jabber/app/helpers/user_helper.rb
module UserHelper
end

jabber/app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jabber/app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

jabber/app/views/friendships/follower.html.erb
<div class="wrapper">
  <h4>Followed by:</h4>
  <% if @follower.length == 0 %>
    <%= "No one" %>
  <% end %>
  <ul>
  <% @follower.each do |friendship| %>
    <li><%= friendship.user.get_name %>&nbsp;
        <%= link_to 'Remove', friendship, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
  </ul>
</div>

jabber/app/views/friendships/following.html.erb
<div class="wrapper">
  <h4>Following:</h4>
  <% if @following.length == 0%>
    <%= "No one" %>
  <% end %>
  <ul>
  <% @following.each do |friendship| %>
    <li><%= friendship.friend.get_name %>&nbsp;
        <%= link_to 'Remove', friendship, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
  </ul>
</div>

jabber/app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

jabber/app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

jabber/app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>
<div class="message-box"
  <p>
    <strong>
      <%= @friendship.user.get_name %> is now following <%= @friendship.friend.get_name %>
    </strong>
  </p>
  <%= link_to 'Back', root_path %>
</div>

jabber/app/views/jabber/_form.html.erb
<%= simple_form_for @jabber do |f| %>
  <%= f.input :message, label: "Your message:", as: :text, :input_html => {:rows => 5, :cols => 40} %>
  <%= f.button :submit, "Jabber!!" %>
<% end %>

jabber/app/views/jabber/_jabber.html.erb
<% jabbers.each do |jabber| %>
  <p><b> &nbsp;&nbsp;<%= jabber.user.get_name %> &nbsp; <%=time_ago_in_words(jabber.created_at) %> ago</b></p>
  <p>&nbsp;&nbsp;<%= jabber.message %></p>
<% end %>

jabber/app/views/jabber/create.html.erb
<h1>Jabber#create</h1>
<p>Find me in app/views/jabber/create.html.erb</p>

jabber/app/views/jabber/index.html.erb
<% if user_signed_in? %>
  <%= render 'user/info' %>
  <%= simple_form_for @jabber, :html=> { class: 'wrapper' } do |f| %>
    <%= f.input :message, label: "Your message:", as: :text, :input_html => {:rows => 5, :cols => 40} %>
    <%= f.button :submit, "Jabber!!" %>
  <% end %>
  <%= render 'jabber' %>
<% end %>

jabber/app/views/jabber/show.html.erb
<h1>Jabber#show</h1>
<p>Find me in app/views/jabber/show.html.erb</p>

jabber/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="active"><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Home", root_path %></li>
            <li><%= image_tag("yoga.png", size:"50x50",class: "thumbnail") %></li>
            <li><%= link_to "View my profile", show_user_path %></li>
            <li><%= link_to 'Edit my profile', edit_user_path %></li>
          <% else %>
            <li class="active"><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li
          <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

jabber/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


</head>
<body class="main">
  <%= render partial: "layouts/navbar" %>
  <%= yield %>
</body>
</html>

jabber/app/views/user/_form.html.erb
<%= simple_form_for @user, :html => {class: "wrapper"} do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text, :input_html => {:rows => 5, :cols => 20}  %>
    <%= f.input :location %>
    <br>
    <%= f.button :submit, "Update" %>
<% end %>

jabber/app/views/user/_info.html.erb
  <p><b>
    Jabbers: <%=current_user.jabbers.count%>,
    Following: <%= link_to current_user.friendships.count, following_path %>
    Followed by: <%= link_to current_user.inverse_friendships.count, follower_path %>
  </b></p>

jabber/app/views/user/_listfriends.html.erb
<ul>
  <% new_friends.each do |user| %>
    <li>
      <%= user.get_name %>
      <%=  link_to "Follow", friendships_path(:friend_id => user), method: :post %>
    </li>
  <% end %>
<ul>

jabber/app/views/user/edit.html.erb
<%= render 'form' %>

jabber/app/views/user/index.html.erb
<div class="container">
  <div id="sidebar">
    <%= render partial: 'listfriends', :locals => { new_friends: @new_friends} %>
  </div>
  <%= render partial: 'info' %>
  <div id = "main-content">
    <%= render partial: 'jabber/form' %>
    <br><br>
    <%= render partial: 'jabber/jabber', :locals => { jabbers: @all_my_jabbers} %>
</div>
</div>

jabber/app/views/user/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'info' %>

<div class="wrapper">

<p>
  <strong>Screen name:</strong>
  <%= current_user.get_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= current_user.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= current_user.location %>
</p>
</div>