day26/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to: "page#index"

  get 'movies' => "page#movies", as: 'movies'
  get 'hobbies' => "page#hobbies", as: 'hobbies'
  get 'cuisine' =>  "page#cuisine", as: 'cuisine'

end

day26/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :trackable, :validatable
end

day26/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

day26/app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :authenticate_user!, only: [:index, :movies, :cuisine, :hobbies]
  def index
  end

  def movies
  end

  def cuisine
  end

  def hobbies
  end

end

day26/app/helpers/application_helper.rb
module ApplicationHelper
end

day26/app/helpers/page_helper.rb
module PageHelper
end

day26/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="active"><%=link_to "Home", root_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Movies", movies_path %></li>
            <li><%= link_to "Cuisine", cuisine_path %></li>
            <li><%= link_to "Hobbies", hobbies_path %></li>
          <% else %>
            <li class="active"><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

day26/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Day26</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render partial: "layouts/navbar" %>
  <%= yield %>

</body>
</html>

day26/app/views/page/cuisine.html.erb
<div class= "container" >
  <h5>My favorite cuisines:</h5>
  <ul>
    <li> Indian. </li>
    <li> Italian. </li>
    <li> Mediterranean. </li>
  </ul>
</div>

day26/app/views/page/hobbies.html.erb
<div class= "container" >
  <h5>My hobbies:</h5>
  <ul>
    <li> Chicklits. </li>
    <li> Code. </li>
    <li> Dance. </li>
  </ul>
</div>

day26/app/views/page/index.html.erb
<p><b>Welcome to my page </b></p>

day26/app/views/page/movies.html.erb
<div class= "container" >
  <h5>My favorite movies:</h5>
  <ul>
    <li> Men in black. </li>
    <li> Matrix . </li>
    <li> Kung-fu panda. </li>
  </ul>
</div>